### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by joserick** [multicaret/laravel-inbox#3]
I can not install multicaret/laravel-inbox in laravel 8. I get the following error:

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - multicaret/laravel-inbox[v7.0, ..., v7.x-dev] require illuminate/support 7.* -> found illuminate/support[v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires multicaret/laravel-inbox ^7.0 -> satisfiable by multicaret/laravel-inbox[v7.0, v7.x-dev].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
@pheeque I see that your fork, you added support for laravel 8, if you had no problems, could you please send a pull request,

**Comment by pheeque** [comment]
I have a project still making use of it and I see no reason why not. Here you go #4

**Comment by mkwsra** [comment]
Merged thank you guys, and I'm super sorry for the huge amount of bugs in this library I'm gonna upload a newer version we made as a team but not right away as we still work on refining it
